### ISSUE TITLE
Bottom Corner Menu doesn't display on IDA Mac

### ISSUE THREAD

**Issue by Maximus-** [IDAConnect/IDAConnect#2]
On IDA 7 for Mac, the bottom corner menu doesn't render. I can right click on it just fine to use it for now. 

Images attached
<img width="352" alt="screen shot 2018-03-27 at 10 22 53 pm" src="https://user-images.githubusercontent.com/628527/38005138-83dd1600-320d-11e8-97cf-3670b1ed0ad8.png">

Right click: 
<img width="361" alt="screen shot 2018-03-27 at 10 25 19 pm" src="https://user-images.githubusercontent.com/628527/38005196-c2131a50-320d-11e8-8167-4189047ecb5d.png">

(Good work on this by the way so far. Really enjoying it :))

**Comment by o0xmuhe** [comment]
I cannot see this Button too..

**Comment by patathor** [comment]
I have made a VM of macOS High Sierra w/ a IDA 7.0 install, but I haven't been able to reproduce the issue.
Here is a screenshot of what I get: 
![tmp](https://user-images.githubusercontent.com/12370545/38056013-846ae510-32db-11e8-98f5-e08394447a03.png)
 Could you give me more information about your system (macOS version, IDA version, etc.) so that I can investigate further. Thanks!

**Comment by NeatMonster** [comment]
@Maximus- @o0xmuhe I fixed the background rendering issue that is visible on @patathor screenshot, but I'm wondering if maybe it also fixed your issue. Can you try a version greater or equal to ef8e0eabdcc7ddc19d13ec1c5ca828fe66138e7a?

**Comment by o0xmuhe** [comment]
@patateqbool  My macOS version is 10.13.4 ,and my IDA Pro version is 7.0.170914. Here is a screenshot  what I got  :
<img width="648" alt="ida" src="https://user-images.githubusercontent.com/12029365/38247531-4277cbfe-3778-11e8-904c-c84d7b4fd6db.png">

I cannot get  Netwrok settings menu,even though I click it.

**Comment by NeatMonster** [comment]
@Maximus- @o0xmuhe I have successfully reproduced the issue on some real hardware. It was an issue w/ high pixel density displays. It should be fixed by commit 0d44756015df1720567ed3309d77e83560b86f44. I will now close this issue.
